name = "cf-rss-aggregator"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[triggers]
crons = [ "*/30 * * * *" ]

[[kv_namespaces]]
binding = "FEEDS_KV"
id = "ab511a30b6d847958238ab6904c467c2"
preview_id = "11111111111111111111111111111111"

[vars]
ADMIN_TOKEN = "change-me"
CORS_ALLOW_ORIGIN = "*"
CACHE_TTL_SECONDS = "900"
FETCH_TIMEOUT_MS = "15000"
CONCURRENCY = "6"
USER_AGENT = "cf-rss-aggregator/0.1"
GROUPS_JSON = """{
  \"friends\": [
    { \"url\": \"https://blog.liushen.fun/atom.xml\", \"author\": \"清羽飞扬\" },
    { \"url\": \"https://www.2x.nz/rss.xml\", \"author\": \"2X\" }
  ]
}"""
CONFIG_URL = ""
